server:
  port: 11111
spring:
#  cloud:
#    consul:
#      discovery:
#        instance-id: ${spring.application.name}:${server.port}
#        prefer-ip-address: true
#        health-check-interval: 10s
#        hostname: ${spring.application.name}
#        service-name: ${spring.application.name}
#        enabled: true
#      host: localhost
#      port: 8500
  application:
    name: pet_zuul
  profiles:
    active: dev




ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000


---
# 开发
spring:
  profiles: dev

eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:90/eureka
    fetch-registry: true
    register-with-eureka: true