server:
  port: 11112
  servlet:
    context-path: /

spring:
  application:
    name: user
  profiles:
    active: dev

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 15
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: userHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1



---

# 开发配置
spring:
  profiles: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.60.79:3306/pet?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: wxyj
    password: 123456

eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:80/eureka
    fetch-registry: true
    register-with-eureka: true