server:
  port: 11113
spring:
  application:
    name: oss
#  cloud:
#    consul:
#      discovery:
#        instance-id: ${spring.application.name}:${server.port}
#        prefer-ip-address: true
#        health-check-interval: 10s
#        hostname: ${spring.application.name}
#        service-name: ${spring.application.name}
#        enabled: true
#        health-check-path: /health
#      host: localhost
#      port: 8500
  profiles:
    active: dev
zuul:
  routes:
    user:
      path: /oss/**
      serviceId: pet_zuul
feign:
  hystrix:
    enabled: false

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

---
# 开发配置
spring:
  profiles: dev


eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:90/eureka
    fetch-registry: true
    register-with-eureka: true


---