server:
  port: 11114
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: home
  profiles:
    active: dev

mybatis-plus:
  # xml地址
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔 #自己的实体类地址
  type-aliases-package: com.pet.common.entity
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名法
    map-underscore-to-camel-case: true
---
# 开发配置
spring:
  profiles: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.60.79:3306/pet?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: wxyj
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
#    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:90/eureka
    fetch-registry: true
    register-with-eureka: true


---