server:
  port: 11113
spring:
  application:
    name: oss
  profiles:
    active: dev

feign:
  hystrix:
    enabled: false

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

---
# 开发配置
spring:
  profiles: dev

eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:80/eureka
    fetch-registry: true
    register-with-eureka: true


---