server:
  port: 9002
spring:
  application:
    name: oss
  profiles:
    active: dev

---
# 开发配置
spring:
  profiles: dev

## 日志
#logging:
#  path: C:/Desktop/dmuser/oss            #.C:/Desktop/dmuser/oss
#
#server:
#  tomcat:
#    basedir: D:/logs


---