
#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: eureka1
#server:
#  port: 80
#eureka:
#  instance:
#    hostname: eureka1
#    prefer-ip-address: false
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.1.161:80/eureka
#    fetch-registry: true
#    register-with-eureka: true
#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: eureka2
#server:
#  port: 80
#eureka:
#  instance:
#    hostname: eureka2
#    prefer-ip-address: false
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.1.160:80/eureka
#    fetch-registry: true
#    register-with-eureka: true

server:
  port: 90

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


