server:
  port: 9000
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
  application:
    name: pet_zuul
  profiles:
    active: dev




feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000



zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

---
# 开发
spring:
  profiles: dev